### ISSUE TITLE
testing is missing

### ISSUE THREAD

**Issue by rkmax** [bixlabs/bix-notifications#1]
Tests are fundamental to write robust and reliable software :smiley_cat: 

packages like:

- https://www.npmjs.com/package/mocha
- https://www.npmjs.com/package/istanbul

Are really helpful

**Comment by EddSuarez** [comment]
Thanks, @rkmax. I think we are going to use **cucumber** for all our modules :D

**Comment by rkmax** [comment]
But what a wonderful news. Lookig forward :blush:

**Comment by jac1013** [comment]
Hey Guys @rkmax @EddSuarez , question here, I don't see much advantage of using _cucumber_ considering that we are creating modules, I like the idea of _cucumber_ a lot for business logic but I don't think its worth for what we want to create here, _mocha_ should be fine, what do you think?

**Comment by rkmax** [comment]
@jac1013 @evasquez26 I think this was closed by #22 right?

**Comment by jac1013** [comment]
Yes.
