### ISSUE TITLE
Minify/uglify build

### ISSUE THREAD

**Issue by EddSuarez** [bixlabs/bix-notifications#21]

**Comment by rkmax** [comment]
@EddSuarez I think this no matters on server side or could you please explain your point

**Comment by EddSuarez** [comment]
@rkmax yes, I think minifying the code will increase the performace. What do you think about [this](https://top.fse.guru/nodejs-a-quick-optimization-advice-7353b820c92e)?

**Comment by jac1013** [comment]
We were talking about this @rkmax but you weren't in the meeting, the thing is that the code is already ugly haha, but I'm not sure if this will have an impact in the performance being in the server side.

**Comment by jac1013** [comment]
Now thinking a little bit more, this is not possible, if we minify the code we will lose the names of the controllers, NotificationController would be transformed into something like ``ca`` :fearful:

**Comment by rkmax** [comment]
@EddSuarez in some moment have readed that article, later readed another that opposites it, at least for me the gain can be minimum, of course the only way to see if works is do it xD
