### ISSUE TITLE
Let's use promises instead of callback.

### ISSUE THREAD

**Issue by jac1013** [bixlabs/bix-notifications#6]

**Comment by rkmax** [comment]
:trollface:

**Comment by acabreragnz** [comment]
Promises the best!

**Comment by rkmax** [comment]
I think we should adopt a hybrid solution, that allow integrate better the module to any project

```js
Object.method().then((result) => {...}).catch((err) => {...})
```

```js
Object.method((err, result) => {...})
```


Even we dont need to implement both on the source code, we can use something like [promisify](http://bluebirdjs.com/docs/api/promise.promisify.html)

**Comment by acabreragnz** [comment]
Epaaaa, totally agree

**Comment by jac1013** [comment]
@rkmax please clarify that the _promisification_ must be done only for the public API of the module, if possible, create an issue to make it even clearer, we agreed on using promises inside of the module not on how to expose it :sweat_smile: , I agree with your comment

**Comment by rkmax** [comment]
@jac1013 Of course. just public API
